
name: Post Review Build URL to PR
on:
  pull_request:
    types: [opened]
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: actions/checkout@v2
        with:
          branch_pattern: 'feature'
          comment_for_invalid_branch_name: 'This branch name is not following the standards. Name should start with feature/'
          fail_if_invalid_branch_name: 'true'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
